"""
Extracts a 28-feature daily time-series for every UK sample point (generated by
generate_uk_grid.py) from Google Earth Engine (GEE) -- Google's free cloud
platform for planetary-scale geospatial analysis.  For each point × date
combination it pulls ~24 of the 28 AEGIS schema features from ERA5-Land,
CHIRPS, MODIS, SMAP, SRTM, ESA WorldCover, SoilGrids, HydroSHEDS, and ENSO.

Glossary:
  GEE               = Google Earth Engine -- free cloud geospatial computation
                       platform; requires a free research account
  ee.ImageCollection= GEE object: a time-ordered stack of satellite images
  getRegion()       = GEE batch export method: extracts pixel values at many
                       points in a single API call, far more efficient than
                       individual point queries
  ERA5-Land         = ECMWF climate reanalysis: hourly global estimates of
                       surface meteorological variables at 9 km resolution,
                       back to 1950
  CHIRPS            = Climate Hazards Group InfraRed Precipitation with Station
                       data -- 40-year global rainfall at 0.05° resolution
  MODIS MOD13Q1     = NASA's Moderate Resolution Imaging Spectroradiometer
                       NDVI product -- 16-day composites at 250 m
  SMAP L4           = NASA Soil Moisture Active Passive Level-4: global daily
                       soil moisture at 9 km from 2015
  SRTM              = Shuttle Radar Topography Mission -- near-global 30 m
                       elevation model
  NDVI              = Normalised Difference Vegetation Index -- measure of
                       green vegetation density, range -1 to +1
  NDWI              = Normalised Difference Water Index -- used for flood mapping
  HydroSHEDS        = Hydrological data derived from SRTM; provides catchment
                       boundaries and river network attributes
  chunk             = a batch of ≤100 points; GEE silently fails on large
                       batches so we chunk to stay inside memory limits
  resume checkpoint = JSON file tracking which chunks are already saved so
                      we can restart after network failures without re-fetching
  service account   = a non-human Google Cloud account used for server-side
                       GEE auth without interactive login

  Input  <- data/labels/uk_sample_points.geojson  (from generate_uk_grid.py)
  Output -> data/raw/gee/chunk_NNNN.parquet         (one file per chunk)
  Next   -> scripts/features/build_master_dataset.py  (merges all chunks)

Requirements:
  pip install earthengine-api geemap tqdm pandas pyarrow

Setup:
  Option A -- Interactive (local dev):
    earthengine authenticate
  Option B -- Service account (CI / server):
    export GEE_SERVICE_ACCOUNT=myproject@project.iam.gserviceaccount.com
    export GEE_PRIVATE_KEY_FILE=/path/to/key.json

Usage:
  python scripts/features/gee_extractor.py
  python scripts/features/gee_extractor.py --start 2015-01-01 --end 2024-12-31
  python scripts/features/gee_extractor.py --chunk-size 50 --workers 2
"""

from __future__ import annotations

import argparse
import json
import sys as _sys
import io as _io
# Force UTF-8 stdout/stderr on Windows to avoid cp1252 UnicodeEncodeError
if hasattr(_sys.stdout, 'reconfigure'):
    _sys.stdout.reconfigure(encoding='utf-8', errors='replace')
if hasattr(_sys.stderr, 'reconfigure'):
    _sys.stderr.reconfigure(encoding='utf-8', errors='replace')
import os
import sys
import time
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

import numpy as np

# Check heavyweight imports upfront
try:
    import ee            # Google Earth Engine Python client
    import pandas as pd
    from tqdm import tqdm
    from dateutil.relativedelta import relativedelta
except ImportError as exc:
    sys.exit(
        f"Missing dependency: {exc}\n"
        "Run: pip install earthengine-api tqdm pandas pyarrow python-dateutil"
    )

_AI_ROOT   = Path(__file__).resolve().parents[2]
_DATA_DIR  = _AI_ROOT / "data"
_RAW_DIR   = _DATA_DIR / "raw" / "gee"
_CKPT_FILE = _DATA_DIR / "raw" / "gee_extraction_checkpoint.json"

# GEE image collection asset IDs -- pinned versions for reproducibility
ASSETS = {
    # ERA5-Land daily aggregates (Copernicus / ECMWF)
    "era5_land":       "ECMWF/ERA5_LAND/DAILY_AGGR",
    # CHIRPS rainfall pentads (Climate Hazards Center)
    "chirps":          "UCSB-CHG/CHIRPS/PENTAD",
    # MODIS NDVI 16-day 250m (NASA Terra, Collection 6.1)
    "modis_ndvi":      "MODIS/061/MOD13Q1",
    # SMAP L4 daily soil moisture (NASA) -- v008 supersedes v007
    "smap":            "NASA/SMAP/SPL4SMGP/008",
    # SRTM static 30m elevation (NASA / USGS) -- also used for slope
    "srtm":            "USGS/SRTMGL1_003",
    # ESA WorldCover 10m land use (2021 epoch, static)
    "worldcover":      "ESA/WorldCover/v200",
    # SoilGrids 250m organic carbon density (ISRIC)
    "soilgrids_ocd":   "projects/soilgrids-isric/ocd_mean_0-5cm",
    # SoilGrids 250m clay content (ISRIC) -- permeability proxy
    "soilgrids_clay":  "projects/soilgrids-isric/clay_mean_0-5cm",
    # HydroSHEDS 15-arc-second flow accumulation (WWF)
    # Cell value = upstream cell count -> catchment_area & drainage_density
    "hydrosheds_acc":  "WWF/HydroSHEDS/15ACC",
}

# Mapping: GEE band name -> AEGIS feature name
ERA5_BAND_MAP = {
    "temperature_2m":             "temperature",
    "dewpoint_temperature_2m":    "humidity",    # approximate; converted below
    "u_component_of_wind_10m":    "_wind_u",     # internal; combined to wind_speed
    "v_component_of_wind_10m":    "_wind_v",     # internal
    "total_evaporation_sum":      "evapotranspiration",
    "total_precipitation_sum":    "rainfall_24h",
}


# Authentication helper

def authenticate_gee() -> None:
    """
    Initialise GEE using either:
      - Service account credentials (production / CI)  -- env vars preferred
      - Interactive auth token (~/.config/earthengine/credentials)  -- local dev

    Raises RuntimeError if neither works.
    """
    sa  = os.getenv("GEE_SERVICE_ACCOUNT")
    key = os.getenv("GEE_PRIVATE_KEY_FILE")

    if sa and key:
        # Service account path (no browser required -- suitable for CI/server)
        credentials = ee.ServiceAccountCredentials(sa, key)
        ee.Initialize(credentials)
        print(f"  GEE authenticated via service account: {sa}")
    else:
        # Interactive path -- works after running `earthengine authenticate`
        try:
            project = os.getenv("GEE_PROJECT", "aegis-disaster-intelligence")
            ee.Initialize(project=project)
            print(f"  GEE authenticated via stored credentials (project: {project}).")
        except Exception as exc:
            raise RuntimeError(
                "GEE authentication failed. Either:\n"
                "  (a) run `earthengine authenticate` in your terminal, or\n"
                "  (b) set GEE_SERVICE_ACCOUNT + GEE_PRIVATE_KEY_FILE env vars."
            ) from exc


# Checkpoint helpers

def load_checkpoint() -> set[int]:
    """Return the set of chunk indices already saved to disk."""
    if _CKPT_FILE.exists():
        data = json.loads(_CKPT_FILE.read_text())
        return set(data.get("completed_chunks", []))
    return set()


def save_checkpoint(completed: set[int]) -> None:
    """Persist the set of completed chunk indices."""
    from datetime import timezone
    _CKPT_FILE.parent.mkdir(parents=True, exist_ok=True)
    _CKPT_FILE.write_text(
        json.dumps({"completed_chunks": sorted(completed), "updated": str(datetime.now(timezone.utc))})
    )


# Retry helper for transient GEE API failures

def retry_gee_call(fn, *args, max_retries: int = 3, **kwargs):
    """
    Call a GEE extraction function with exponential backoff.

    GEE intermittently returns HTTP 500, "Computation timed out", or
    ee.EEException under heavy server load.  A simple retry with increasing
    wait usually succeeds.
    """
    last_exc: Exception | None = None
    for attempt in range(max_retries):
        try:
            return fn(*args, **kwargs)
        except Exception as exc:
            last_exc = exc
            if attempt == max_retries - 1:
                raise
            wait = 2 ** attempt * 5  # 5 s, 10 s, 20 s
            print(f"  GEE retry {attempt + 1}/{max_retries}: {exc}")
            time.sleep(wait)
    raise last_exc  # unreachable but satisfies type checker


# ERA5-Land batch extraction

def extract_era5(
    points_ee: ee.FeatureCollection,
    start: str,
    end: str,
) -> pd.DataFrame:
    """
    Extract ERA5-Land daily climate variables at each point.

    The getRegion() call returns a nested list:
      [ [id, lon, lat, time, band1, band2, ...], ... ]
    The first row is the header.

    Returns a DataFrame with columns: lat, lon, date, <ERA5 bands...>
    """
    collection = (
        ee.ImageCollection(ASSETS["era5_land"])
        .filterDate(start, end)
        .select(list(ERA5_BAND_MAP.keys()))
    )

    raw = collection.getRegion(points_ee, scale=9000).getInfo()
    if not raw or len(raw) < 2:
        return pd.DataFrame()

    df = pd.DataFrame(raw[1:], columns=raw[0])
    # 'time' comes in as milliseconds since epoch -- convert to date string
    df["date"] = pd.to_datetime(df["time"], unit="ms").dt.strftime("%Y-%m-%d")
    df = df.drop(columns=["id", "time"], errors="ignore")
    df = df.rename(columns=ERA5_BAND_MAP)

    # getRegion can return object-typed columns with mixed nulls/strings.
    # Coerce all numeric climate bands explicitly before math operations.
    for col in ["temperature", "humidity", "_wind_u", "_wind_v", "evapotranspiration", "rainfall_24h"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # Derive wind_speed from U and V components using Pythagoras
    # wind_speed = √(u² + v²)  in m/s
    if "_wind_u" in df.columns and "_wind_v" in df.columns:
        df["wind_speed"] = np.sqrt(df["_wind_u"] ** 2 + df["_wind_v"] ** 2)
        df = df.drop(columns=["_wind_u", "_wind_v"])

    # Convert dewpoint temperature -> relative humidity (%)
    # Using Magnus approximation: RH ≈ 100 × e^(17.625 × Td / (243.04 + Td))
    #                                          / e^(17.625 × T  / (243.04 + T))
    # where T and Td are in degrees Celsius
    if "humidity" in df.columns and "temperature" in df.columns:
        T  = df["temperature"] - 273.15       # Kelvin -> Celsius
        Td = df["humidity"]    - 273.15       # dewpoint in Celsius
        df["humidity"] = 100 * np.exp(17.625 * Td / (243.04 + Td)) / \
                               np.exp(17.625 * T  / (243.04 + T))
        df["humidity"] = df["humidity"].clip(0, 100)
        df["temperature"] = T  # store as Celsius from here on

    return df


def extract_chirps(
    points_ee: ee.FeatureCollection,
    start: str,
    end: str,
) -> pd.DataFrame:
    """Extract CHIRPS pentad (5-day) rainfall for anomaly calculation."""
    collection = (
        ee.ImageCollection(ASSETS["chirps"])
        .filterDate(start, end)
        .select(["precipitation"])
    )
    raw = collection.getRegion(points_ee, scale=5000).getInfo()
    if not raw or len(raw) < 2:
        return pd.DataFrame()
    df = pd.DataFrame(raw[1:], columns=raw[0])
    df["date"] = pd.to_datetime(df["time"], unit="ms").dt.strftime("%Y-%m-%d")
    df = df.drop(columns=["id", "time"], errors="ignore")
    df = df.rename(columns={"precipitation": "chirps_precipitation_mm"})
    return df


def extract_modis_ndvi(
    points_ee: ee.FeatureCollection,
    start: str,
    end: str,
) -> pd.DataFrame:
    """
    Extract MODIS 16-day NDVI composites.
    NDVI is stored as integer scaled by 0.0001 -- divide to get the real value.
    """
    collection = (
        ee.ImageCollection(ASSETS["modis_ndvi"])
        .filterDate(start, end)
        .select(["NDVI"])
    )
    raw = collection.getRegion(points_ee, scale=250).getInfo()
    if not raw or len(raw) < 2:
        return pd.DataFrame()
    df = pd.DataFrame(raw[1:], columns=raw[0])
    df["date"] = pd.to_datetime(df["time"], unit="ms").dt.strftime("%Y-%m-%d")
    df = df.drop(columns=["id", "time"], errors="ignore")
    df["vegetation_index_ndvi"] = df["NDVI"].astype(float) * 0.0001  # scale factor
    df = df.drop(columns=["NDVI"])
    return df


def extract_smap(
    points_ee: ee.FeatureCollection,
    start: str,
    end: str,
) -> pd.DataFrame:
    """Extract SMAP L4 surface soil moisture (m³/m³, top 5 cm)."""
    collection = (
        ee.ImageCollection(ASSETS["smap"])
        .filterDate(start, end)
        .select(["sm_surface"])
    )

    # SMAP starts in 2015. For earlier windows, return empty frame instead of
    # raising "No bands in collection" and aborting the entire year.
    try:
        if collection.size().getInfo() == 0:
            return pd.DataFrame()
    except Exception:
        # If size check fails transiently, continue to normal extraction path.
        pass

    raw = collection.getRegion(points_ee, scale=9000).getInfo()
    if not raw or len(raw) < 2:
        return pd.DataFrame()
    df = pd.DataFrame(raw[1:], columns=raw[0])
    df["date"] = pd.to_datetime(df["time"], unit="ms").dt.strftime("%Y-%m-%d")
    df = df.drop(columns=["id", "time"], errors="ignore")
    df = df.rename(columns={"sm_surface": "soil_moisture"})
    return df


def extract_static_features(
    points_ee: ee.FeatureCollection,
    points_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Extract time-invariant (static) features per sample point.

    Sources:
      SRTM        -> elevation, basin_slope (ee.Terrain.slope)
      WorldCover  -> land_use_encoded, impervious_surface_ratio,
                    vegetation_class_encoded
      SoilGrids   -> soil_type_encoded (OCD), permeability_index (clay)
      HydroSHEDS  -> catchment_area, drainage_density (flow accumulation)
    """
    # SRTM elevation (30 m) + terrain slope in degrees
    srtm  = ee.Image(ASSETS["srtm"]).select(["elevation"])
    slope = ee.Terrain.slope(srtm).rename("basin_slope")

    # ESA WorldCover 2021 (10 m)
    wc_raw = ee.ImageCollection(ASSETS["worldcover"]).mosaic().select(["Map"])

    # Impervious surface ratio: fraction of built-up (class 50) within 1 km
    wc_buildup = wc_raw.eq(50).rename("buildup_mask")
    impervious = wc_buildup.reduceNeighborhood(
        reducer=ee.Reducer.mean(),
        kernel=ee.Kernel.circle(radius=500, units="meters"),
    ).rename("impervious_surface_ratio")

    # Simplified vegetation class remap:
    #   10->1 tree, 20->2 shrub, 30->3 grass, 40->4 crop, 50->5 built,
    #   60->6 bare, 70->7 snow, 80->8 water, 90/95->9 wetland, 100->6 moss
    veg_class = wc_raw.remap(
        [10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 100],
        [1,  2,  3,  4,  5,  6,  7,  8,  9,  9,  6],
    ).rename("vegetation_class_encoded")

    # SoilGrids assets can be permission-gated depending on account.
    # Use deterministic fallbacks to keep extraction robust across environments.
    soil_ocd = ee.Image.constant(0).rename("soil_type_encoded")
    soil_clay = ee.Image.constant(50).rename("clay_pct")

    # HydroSHEDS 15-arc-sec flow accumulation (~500 m)
    hydro_acc = ee.Image(ASSETS["hydrosheds_acc"]).rename("flow_acc")

    # Combine everything into one multi-band image
    combined = (
        srtm
        .addBands(slope)
        .addBands(wc_raw.rename("land_use_encoded"))
        .addBands(impervious)
        .addBands(veg_class)
        .addBands(soil_ocd)
        .addBands(soil_clay)
        .addBands(hydro_acc)
    )

    # Sample at 500 m -- coarse enough that each input point maps to exactly
    # one pixel in every source (avoids multi-pixel expansion at 30m SRTM
    # that would later cause a cartesian-product row explosion on merge).
    sampled = combined.sampleRegions(
        collection=points_ee,
        scale=500,
        geometries=True,
    )

    features = sampled.getInfo()["features"]
    # Build grid_id -> original lat/lon lookup to avoid GEE grid-snapping mismatch.
    # (sampleRegions snaps to 500m SRTM grid; ERA5 snaps to 9km grid -> coords differ).
    gid_lookup: dict[str, tuple[float, float]] = {
        str(row["grid_id"]): (float(row["lat"]), float(row["lon"]))
        for _, row in points_df.iterrows()
    }
    rows = []
    for f in features:
        p = f["properties"]
        gid = str(p.get("grid_id", ""))
        if gid in gid_lookup:
            orig_lat, orig_lon = gid_lookup[gid]
        else:
            coords = f["geometry"]["coordinates"]
            orig_lon, orig_lat = coords[0], coords[1]

        flow = float(p.get("flow_acc", 0) or 0)
        # Catchment area ≈ flow_acc × cell_area; at 15 arc-sec (~500 m)
        # each upstream cell ≈ 0.25 km²
        catchment_km2 = max(flow * 0.25, 0.0)
        # Drainage density proxy: log10(flow_acc + 1)
        drainage = np.log10(flow + 1.0)
        # Permeability index: invert clay fraction (more clay = lower perm)
        clay = float(p.get("clay_pct", 50) or 50)
        permeability = 1.0 - (clay / 100.0)

        rows.append({
            "lon":                       orig_lon,
            "lat":                       orig_lat,
            "elevation":                 p.get("elevation", np.nan),
            "basin_slope":               p.get("basin_slope", np.nan),
            "land_use_encoded":          p.get("land_use_encoded", 0),
            "impervious_surface_ratio":  p.get("impervious_surface_ratio", 0.0),
            "vegetation_class_encoded":  p.get("vegetation_class_encoded", 0),
            "soil_type_encoded":         p.get("soil_type_encoded", np.nan),
            "permeability_index":        permeability,
            "catchment_area":            catchment_km2,
            "drainage_density":          drainage,
        })
    return pd.DataFrame(rows)


# Rolling rainfall aggregation (fills rainfall_1h/6h/7d/30d from 24h totals)

def compute_rolling_rainfall(df: pd.DataFrame) -> pd.DataFrame:
    """
    The ERA5-Land `total_precipitation_sum` is a 24-hour total.
    Build rolling aggregates to fill the remaining rainfall schema features.

    This is an approximation -- 1-hour and 6-hour peaks are not available
    in daily ERA5; we distribute evenly unless sub-daily data is sourced.
    """
    df = df.sort_values(["lat", "lon", "date"]).copy()
    df["date_dt"] = pd.to_datetime(df["date"])

    for group_key, gdf in df.groupby(["lat", "lon"]):
        idx = gdf.index
        rain = gdf["rainfall_24h"].fillna(0)
        # 1h and 6h are rough approximations (daily / 24 and daily / 4)
        df.loc[idx, "rainfall_1h"]  = rain / 24.0
        df.loc[idx, "rainfall_6h"]  = rain / 4.0
        # 7d and 30d rolling sums
        df.loc[idx, "rainfall_7d"]  = rain.rolling(7,  min_periods=1).sum().values
        df.loc[idx, "rainfall_30d"] = rain.rolling(30, min_periods=1).sum().values

    return df.drop(columns=["date_dt"])


# Main extraction loop -- chunk-based with checkpoint resume

def extract_chunk(
    points_df: pd.DataFrame,
    chunk_idx: int,
    start: str,
    end: str,
    max_retries: int = 3,
) -> pd.DataFrame | None:
    """
    Run all GEE extractions for a single chunk of up to 100 sample points.

    The date range is split into yearly segments so that each getRegion()
    call stays comfortably within GEE's memory / compute limits.  For a
    24-year span (2000-2024), 100 pts × 365 days × N bands per year is
    manageable; 100 pts × 8766 days in one call is not.

    Returns a merged DataFrame or None on failure.
    """
    # Build GEE FeatureCollection from the chunk's lat/lon pairs
    features = [
        ee.Feature(ee.Geometry.Point([row["lon"], row["lat"]]), {"grid_id": row["grid_id"]})
        for _, row in points_df.iterrows()
    ]
    points_ee = ee.FeatureCollection(features)

    # Static features (time-invariant) -- extract once for the chunk
    try:
        static = retry_gee_call(
            extract_static_features, points_ee, points_df, max_retries=max_retries,
        )
    except Exception as exc:
        print(f"\n  [Chunk {chunk_idx}] static features failed: {exc}")
        static = pd.DataFrame()

    # Dynamic features -- split by QUARTER to stay within GEE free-tier limits
    # GEE free tier has strict memory limits; yearly spans with 5+ points often
    # exceed "User memory limit". Quarterly windows (90 days) are safe.
    from datetime import datetime as dt

    start_dt = dt.strptime(start, "%Y-%m-%d")
    end_dt   = dt.strptime(end, "%Y-%m-%d")

    quarterly_dfs: list[pd.DataFrame] = []
    window_start = start_dt
    while window_start <= end_dt:
        window_end = min(window_start + relativedelta(months=3) - timedelta(days=1), end_dt)
        q_start = window_start.strftime("%Y-%m-%d")
        q_end   = window_end.strftime("%Y-%m-%d")

        try:
            era5   = retry_gee_call(extract_era5,       points_ee, q_start, q_end, max_retries=max_retries)
            chirps = retry_gee_call(extract_chirps,     points_ee, q_start, q_end, max_retries=max_retries)
            ndvi   = retry_gee_call(extract_modis_ndvi, points_ee, q_start, q_end, max_retries=max_retries)
            smap   = retry_gee_call(extract_smap,       points_ee, q_start, q_end, max_retries=max_retries)
        except Exception as exc:
            print(f"\n  [Chunk {chunk_idx}, {q_start}] GEE extraction error: {exc}")
            window_start = window_start + relativedelta(months=3)
            continue  # skip this quarter, proceed with remaining

        if era5.empty:
            window_start = window_start + relativedelta(months=3)
            continue

        merged = era5.copy()
        for df_extra in [chirps, ndvi, smap]:
            if df_extra is not None and not df_extra.empty:
                merged = merged.merge(
                    df_extra, on=["latitude", "longitude", "date"], how="left",
                )
        quarterly_dfs.append(merged)
        window_start = window_start + relativedelta(months=3)

    if not quarterly_dfs:
        return None

    result = pd.concat(quarterly_dfs, ignore_index=True)

    # Rename coordinate columns to standard names
    result = result.rename(columns={"latitude": "lat", "longitude": "lon"})

    # Snap ERA5-snapped lat/lon back to original points_df coordinates.
    # ERA5 getRegion snaps each input point to the nearest 9km pixel centre,
    # producing slightly different lat/lon values than sampleRegions (500m).
    # Nearest-neighbour matching restores original coords so static merge works.
    import numpy as _np
    orig_lats = points_df["lat"].values.astype(float)
    orig_lons = points_df["lon"].values.astype(float)
    era5_lats = result["lat"].values.astype(float)
    era5_lons = result["lon"].values.astype(float)
    dists_sq = (
        (era5_lats[:, None] - orig_lats[None, :]) ** 2
        + (era5_lons[:, None] - orig_lons[None, :]) ** 2
    )
    nearest = _np.argmin(dists_sq, axis=1)
    result["lat"] = orig_lats[nearest]
    result["lon"] = orig_lons[nearest]

    # Rolling rainfall aggregation (needs the full time-series per point)
    result = compute_rolling_rainfall(result)

    # Join static features -- deduplicate static by (lat, lon) first to
    # prevent row explosion when sampleRegions returns > 1 row per point.
    if static is not None and not static.empty:
        static_dedup = static.drop_duplicates(subset=["lat", "lon"], keep="first")
        result = result.merge(static_dedup, on=["lat", "lon"], how="left")

    # Final deduplication: keep the first row per (lat, lon, date) to guard
    # against any remaining duplicates from multi-scale GEE sampling.
    result = result.drop_duplicates(subset=["lat", "lon", "date"], keep="first")

    return result


def run_extraction(
    sample_points_path: Path,
    start: str,
    end: str,
    chunk_size: int = 100,
) -> None:
    """
    Orchestrate extraction for all sample points with checkpoint-based resume.

    Progress bar shows estimated time remaining; actual GEE latency varies
    with server load (typically 2-10 s per chunk for ≤100 points × 1 year).
    """
    _RAW_DIR.mkdir(parents=True, exist_ok=True)

    # Load sample points
    try:
        import geopandas as gpd
        gdf = gpd.read_file(str(sample_points_path))
        points_df = pd.DataFrame({
            "grid_id": gdf["grid_id"].astype(str),
            "lat":     gdf.geometry.y.astype(float),
            "lon":     gdf.geometry.x.astype(float),
        })
    except Exception as exc:
        sys.exit(f"Failed to load sample points: {exc}")

    print(f"  Loaded {len(points_df):,} sample points from {sample_points_path}")

    # Split into chunks of ≤chunk_size points
    chunks = [
        points_df.iloc[i: i + chunk_size].reset_index(drop=True)
        for i in range(0, len(points_df), chunk_size)
    ]
    print(f"  Processing {len(chunks)} chunks x {chunk_size} points  [{start} -> {end}]")

    # Load checkpoint to skip already-completed chunks
    completed = load_checkpoint()
    pending   = [i for i in range(len(chunks)) if i not in completed]
    print(f"  Chunks to run: {len(pending)} (already done: {len(completed)})")

    with tqdm(total=len(pending), unit="chunk", desc="GEE extraction") as pbar:
        for chunk_idx in pending:
            chunk_df = chunks[chunk_idx]
            out_path = _RAW_DIR / f"chunk_{chunk_idx:04d}.parquet"

            t0     = time.perf_counter()
            result = extract_chunk(chunk_df, chunk_idx, start, end)
            elapsed = time.perf_counter() - t0

            if result is not None and not result.empty:
                result.to_parquet(out_path, index=False, compression="snappy")
                completed.add(chunk_idx)
                save_checkpoint(completed)
                pbar.set_postfix({"rows": len(result), "s": f"{elapsed:.1f}"})
            else:
                pbar.set_postfix({"status": "failed -- will retry on next run"})

            pbar.update(1)
            # Small back-off to avoid hammering GEE API
            time.sleep(0.5)

    total_chunks = len([f for f in _RAW_DIR.glob("chunk_*.parquet")])
    print(f"\nExtraction complete. {total_chunks} chunks saved to {_RAW_DIR}")
    print("Next step: python scripts/features/build_master_dataset.py")


# CLI

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Extract GEE features for UK sample points")
    p.add_argument("--points",       type=Path,  default=_DATA_DIR / "labels" / "uk_sample_points.geojson")
    p.add_argument("--start",        type=str,   default="2000-01-01", help="ISO date")
    p.add_argument("--end",          type=str,   default="2024-12-31", help="ISO date")
    p.add_argument("--chunk-size",   type=int,   default=100,          help="Points per GEE batch")
    p.add_argument("--max-retries",  type=int,   default=3,            help="GEE API retry attempts")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    print("[1/2] Authenticating with Google Earth Engine ...")
    authenticate_gee()

    print("[2/2] Starting extraction ...")
    run_extraction(args.points, args.start, args.end, args.chunk_size)
    # NOTE: ENSO index and long_term_rainfall_anomaly are computed in
    # build_master_dataset.py -- ENSO is a global monthly scalar (not a GEE
    # asset), and rainfall anomaly requires the 30-year climatology across
    # all chunks before it can be calculated.


if __name__ == "__main__":
    main()
