/**
 * File: vitest.config.ts
 *
 * What this file does:
 * Vitest unit and integration test configuration for the Aegis client.
 * Runs tests in a jsdom browser emulation environment. Coverage reports
 * are generated by V8 (native, no Babel transform overhead) and saved
 * as HTML + LCOV for CI artefact upload.
 *
 * Key settings:
 * - environment: jsdom    -- DOM APIs available in all test files
 * - globals: true         -- describe/test/expect available without import
 * - setupFiles            -- client/src/__tests__/setup.ts runs before each suite
 * - coverage thresholds   -- minimum 6% statements, 7% lines (incremental)
 *
 * How it connects:
 * - Run with: npm test (from aegis-v6/client/)
 * - Test files in: client/src/__tests__/
 * - Coverage reports in: client/coverage/
 * - CI reads lcov report from coverage/lcov.info
 * - Learn more: https://vitest.dev/config/
 */

import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    environment: 'jsdom',
    globals: true,
    include: ['src/__tests__/**/*.test.{ts,tsx}'],
    setupFiles: ['src/__tests__/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'lcov', 'html'],
      reportsDirectory: 'coverage',
      include: [
        'src/components/citizen/**/*.{ts,tsx}',
        'src/components/shared/**/*.{ts,tsx}',
        'src/components/ui/**/*.{ts,tsx}',
        'src/components/admin/**/*.{ts,tsx}',
        'src/hooks/**/*.ts',
        'src/utils/**/*.ts',
        'src/data/**/*.ts',
      ],
      exclude: ['src/__tests__/**', 'src/**/*.d.ts', 'src/**/*.stories.tsx'],
      //Phase 3 coverage targets - incremental milestones
      //Phase 3.1 (Complete): Foundation tests for critical paths (~5%)
      //Phase 3.2 (Current): 7% coverage (599+ tests, hooks + components)
      //Phase 3.3: 15% coverage (comprehensive utils/hooks)
      //Phase 3.4: 35%+ coverage (world-class standard)
      thresholds: {
        statements: 6,
        branches: 4,
        functions: 4,
        lines: 7,
      },
    },
  },
})
